[pytest]
pythonpath = .
testpaths = tests
python_files = test_*.py
python_functions = test_*
python_classes = Test*

addopts =
    -v
    --strict-markers
    --cov=src
    --cov-report=term-missing

markers =
    csv_reader: Тесты для CSVReader
    median_coffee: Тесты для MedianCoffeeReport
    report_factory: Тесты для ReportFactory
    args_parser: Тесты для ArgsParser
